name: Lint
on: [push, pull_request]

jobs:
  lint_markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove archive docs
        run: |
          rm -rf docs/archive
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: docs/
          filter_mode: nofilter
          fail_on_error: false
      - uses: articulate/actions-markdownlint@main
        with:
          config: .markdownlint.jsonc
          files: 'docs/**/*.md'
